name: "自动获取最新网易新闻热点"
on:
  push:
  schedule:
    # 每天早上8点运行
    - cron: "0 0 * * *"
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  get-news:
    runs-on: ubuntu-latest
    steps:
      - name: "检查仓库"
        uses: actions/checkout@v3
      - name: "编译程序"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install -g hexo-cli
          yarn
          git config --global user.email "cnwwhai@gmail.com"
          git config --global user.name "wwhai"
          hexo g
          ls -al
          # hexo d
          # cd .deploy_git/
          # git push https://github.com/wwhai/wwhai.github.io.git www -f