name: HEXO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [v19.0.1]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Deploy hexo
        run: |
          git config --global user.email "cnwwhai@gmail.com"
          git config --global user.name "wwhai"
          npm install -g hexo-cli
          yarn
          hexo g
          hexo d